---
title: "Peer Review Response"
format: html
editor: visual
---

## Spiro Quality

Differential Spirometry Quality per Race and SDOH. What's the characteristics of those who are excluded because of low quality spiro?

```{r}
library(tidyverse)
library(purrr)
library(naniar)
library(tidymodels)
library(ggthemes)
library(patchwork)
library(hrbrthemes)
library(table1)
library(rspiro)
library(stringr)
library(srvyr)
library(survey)
library(gtsummary)
nhanes <- readRDS("nhanes_2007_2012.rds") %>%
  as_survey_design(
    weights=MEC6YR,
    ids=SDMVPSU,
    strata=SDMVSTRA,
    nest=TRUE
  )  %>%
  mutate(fev1 = fev1_pre,
         fvc  = fvc_pre) %>%
  drop_na(fev1, fvc) %>%
  srvyr::filter ((is.na(current_smoke) | (current_smoke == "3")) &
                   (is.na(ever_100_smoke) | (ever_100_smoke != "1")) &
                   (is.na(last_5_days_cigarettes) |  (last_5_days_cigarettes != "1")) &
                   (is.na(last_5_days_pipes) | (last_5_days_pipes != "1")) &
                   (is.na(last_5_days_cigars) | (last_5_days_cigars != "1")) &
                   (is.na(ever_asthma) | (ever_asthma !="1")) &
                   (is.na(ever_bronchitis) | (ever_bronchitis != "1")) &
                   (is.na(ever_emphysema) | (ever_emphysema != "1")) &
                   (is.na(cough_3_month) | (cough_3_month!=1)) & 
                   (is.na(phlegm_3_month) | (phlegm_3_month!=1)) & 
                   (is.na(wheezing_past_yr) | (wheezing_past_yr!=1)) & 
                   (is.na(dry_cough_night_past_yr) | (dry_cough_night_past_yr!=1))) 



nhanes_included <- nhanes  %>%
  srvyr::filter(spiro_status_pre == 1) %>%
  srvyr::filter(fev1_quality_pre == "A" | fev1_quality_pre == "B") %>%
  srvyr::filter(fvc_quality_pre  == "A" | fvc_quality_pre  == "B")


nhanes_excluded <- nhanes  %>%
  srvyr::filter(!((spiro_status_pre == 1) &
                (fev1_quality_pre == "A" | fev1_quality_pre == "B") & 
                (fvc_quality_pre  == "A" | fvc_quality_pre  == "B"))) %>%
  mutate(age_group = ifelse(age>=20, "Adults", "Children"),
         sex_text   = case_match(sex,
                                 "1" ~ "Male"  ,
                                 "2" ~ "Female" ),
         time_in_us = case_match(time_in_us, 
                                 1 ~ "Less than 1 year",
                                 2 ~ "1 yr., less than 5 yrs.",
                                 3 ~ "5 yrs., less than 10 yrs.",
                                 4 ~ "10 yrs., less than 15 yrs.", 
                                 5 ~ "15 yrs., less than 20 yrs.",
                                 6 ~ "20 yrs., less than 30 yrs.", 
                                 7 ~ "30 yrs., less than 40 yrs.", 
                                 8 ~ "40 yrs., less than 50 yrs.", 
                                 9 ~ "50 years or more", 
                                 77 ~ NA,
                                 99 ~ NA, 
         ),
         has_insurance = case_match(has_insurance, 
                                    1 ~ "Yes",
                                    2 ~ "No",
                                    7 ~ "Refused",
                                    9 ~ "Don't Know", 
         ),
         cough_3_month = case_match(cough_3_month,
                                    1 ~ "Yes"  ,
                                    2 ~ "No"),
         phlegm_3_month = case_match(phlegm_3_month,
                                     1 ~ "Yes"  ,
                                     2 ~ "No"),
         wheezing_past_yr = case_match(wheezing_past_yr,
                                       1 ~ "Yes"  ,
                                       2 ~ "No"),
         dry_cough_night_past_yr = case_match(dry_cough_night_past_yr,
                                              1 ~ "Yes"  ,
                                              2 ~ "No"),
         ever_asthma = case_match(ever_asthma,
                                  "1" ~ "Yes"  ,
                                  "2" ~ "No"),
         ever_bronchitis = case_match(ever_bronchitis,
                                      "1" ~ "Yes"  ,
                                      "2" ~ "No"),
         ever_emphysema = case_match(ever_emphysema,
                                     "1" ~ "Yes"  ,
                                     "2" ~ "No"),
         ever_100_smoke = case_match(ever_100_smoke,
                                     "1" ~ "Yes"  ,
                                     "2" ~ "No"),
         current_smoke = case_match(current_smoke,
                                    "1" ~ "Everyday"  ,
                                    "2" ~ "Some days",
                                    "3" ~ "Not at all"),
         education_adults = case_match(education_adults,
                                       "1" ~ "Less than 9th grade"  ,
                                       "2" ~ "9-11th grade",
                                       "3" ~ "High school graduate",
                                       "4" ~ "Some college or AA degree",
                                       "5" ~ "College graduate or above"),
         education_adults = factor(education_adults, 
                                   levels = c("College graduate or above",
                                              "Some college or AA degree",
                                              "High school graduate",
                                              "9-11th grade",
                                              "Less than 9th grade"
                                   )),
         now_attending_school = case_match(now_attending_school,
                                           1 ~ "In school",
                                           2 ~ "Between grades",
                                           2 ~ "Not in school"),
         smoker_in_household = case_match(smoker_in_household,
                                          1 ~ "Yes",
                                          2 ~ "No"),
         maternal_smoke = case_match(maternal_smoke,
                                     1 ~ "Yes",
                                     2 ~ "No"),
         home_ownership = case_match(home_ownership,
                                     1 ~ "Owned or being bought",
                                     2 ~ "Rented",
                                     3 ~ "Other arrangements"),
         mineral_dusts = case_match(mineral_dusts,
                                    1 ~ "Yes",
                                    2 ~ "No"),
         organic_dusts = case_match(organic_dusts,
                                    1 ~ "Yes",
                                    2 ~ "No"),
         exhaust_fumes = case_match(exhaust_fumes,
                                    1 ~ "Yes",
                                    2 ~ "No"),
         other_fumes = case_match(other_fumes,
                                  1 ~ "Yes",
                                  2 ~ "No"),
         healthy_diet = case_match(healthy_diet,
                                   1 ~ "Excellent",
                                   2 ~ "Very good",
                                   3 ~ "Good",
                                   4 ~ "Fair",
                                   5 ~ "Poor"),
         healthy_diet = factor(healthy_diet, levels = c("Excellent",
                                                        "Very good",
                                                        "Good",
                                                        "Fair",
                                                        "Poor")),
         vigorous_work = case_match(vigorous_work,
                                    1 ~ "Yes",
                                    2 ~ "No"),
         moderate_work = case_match(moderate_work,
                                    1 ~ "Yes",
                                    2 ~ "No"),
         vigorous_recreational = case_match(vigorous_recreational,
                                            1 ~ "Yes",
                                            2 ~ "No"),
         moderate_recreational = case_match(moderate_recreational,
                                            1 ~ "Yes",
                                            2 ~ "No"),
         
         smoker=
           !((is.na(current_smoke) | (current_smoke == "3")) &
               (is.na(ever_100_smoke) | (ever_100_smoke != "1")) &
               (is.na(last_5_days_cigarettes) |  (last_5_days_cigarettes != "1")) &
               (is.na(last_5_days_pipes) | (last_5_days_pipes != "1")) &
               (is.na(last_5_days_cigars) | (last_5_days_cigars != "1"))),
         resp_symptoms = !((is.na(cough_3_month) | (cough_3_month!=1)) & 
                             (is.na(phlegm_3_month) | (phlegm_3_month!=1)) & 
                             (is.na(wheezing_past_yr) | (wheezing_past_yr!=1)) & 
                             (is.na(dry_cough_night_past_yr) | (dry_cough_night_past_yr!=1))),
         resp_dx = !((is.na(ever_asthma) | (ever_asthma !="1")) &
                       (is.na(ever_bronchitis) | (ever_bronchitis != "1")) &
                       (is.na(ever_emphysema) | (ever_emphysema != "1"))),
         physically_active = ((is.na(vigorous_work) | (vigorous_work==1)) | 
                                (is.na(vigorous_recreational)   | (vigorous_recreational==1)) | 
                                (is.na(moderate_work)   | (moderate_work==1)) | 
                                (is.na(moderate_recreational)   | (moderate_recreational==1))),
         occupational_exposure = !((is.na(mineral_dusts) | (mineral_dusts!=1)) & 
                                     (is.na(organic_dusts)   | (organic_dusts!=1)) & 
                                     (is.na(exhaust_fumes)   | (exhaust_fumes!=1)) & 
                                     (is.na(other_fumes)     | (other_fumes!=1))),
         home_owner = (is.na(home_ownership) | (home_ownership==1)), 
         healthy_eater = ((is.na(healthy_diet) | 
                             (healthy_diet==1) | 
                             (healthy_diet==2) | 
                             (healthy_diet==3)))
  ) 


label(nhanes_excluded$variables$race_text_nhanes) <- "Race and Ethnicity"
label(nhanes_excluded$variables$age) <- "Age (years), mean (SD)"
label(nhanes_excluded$variables$fev1) <- "FEV1 (mL), mean (SD)"
label(nhanes_excluded$variables$fvc) <- "FVC (mL), mean (SD)"
label(nhanes_excluded$variables$sex_text) <- "Biological Sex at Birth"
label(nhanes_excluded$variables$birth_country) <- "Birth Country"
label(nhanes_excluded$variables$smoker_in_household) <- "Smoker in Household"
label(nhanes_excluded$variables$maternal_smoke) <- "Maternal smoke during pregnancy (For Children)"
label(nhanes_excluded$variables$mineral_dusts) <- "Occupational Exposure to Mineral Dusts"
label(nhanes_excluded$variables$organic_dusts) <- "Occupational Exposure to Organic Dusts"
label(nhanes_excluded$variables$exhaust_fumes) <- "Occupational Exposure to Exhaust Fumes"
label(nhanes_excluded$variables$other_fumes) <- "Occupational Exposure to Other Fumes"
label(nhanes_excluded$variables$education_adults) <- "Education Level for Adults"
label(nhanes_excluded$variables$now_attending_school) <- "Currently Attending School (for Children)"
label(nhanes_excluded$variables$healthy_diet) <- "Self-reported Diet Health"
label(nhanes_excluded$variables$vigorous_work) <- "Vigorous Activity at Work (10 min/week)"
label(nhanes_excluded$variables$vigorous_recreational) <- "Recreational Vigorous Activity (10 min/week)"
label(nhanes_excluded$variables$moderate_work) <- "Moderate Activity at Work (10 min/week)"
label(nhanes_excluded$variables$moderate_recreational) <- "Recreational Moderate Activity (10 min/week)"
label(nhanes_excluded$variables$bmi) <- "Body Mass Index (kg/m2), mean (SD)"
label(nhanes_excluded$variables$income_poverty_ratio) <- "Income-to-Poverty Ratio"
label(nhanes_excluded$variables$home_owner) <- "Homeowner"
label(nhanes_excluded$variables$has_insurance) <- "Health Insurance"


                  
tbl_svysummary(nhanes_excluded,
               missing = "ifany", 
               by="age_group",
               statistic = list(
                 all_continuous()  ~ "{mean} ({sd})", 
                 all_categorical() ~ "{n_unweighted} ({p}%)"),
               missing_text = "Missing",
               missing_stat = "{N_miss_unweighted} ({p_miss_unweighted}%)",
               digits = list(all_continuous() ~ c(1, 1), all_categorical() ~ c(0, 1)),
               include=c(age,
                         race_text_nhanes, 
                         sex_text,fev1, 
                         fvc,
                         smoker_in_household, 
                         maternal_smoke,
                         mineral_dusts,
                         organic_dusts, 
                         exhaust_fumes, 
                         other_fumes,
                         income_poverty_ratio,
                         home_owner, 
                         has_insurance,
                         education_adults, 
                         now_attending_school,
                         healthy_diet,
                         vigorous_work,
                         moderate_work, 
                         vigorous_recreational,
                         moderate_recreational,
                         bmi))  %>%
  as_flex_table()


```

## LLN Impact

```{r}


library(dplyr)
library(ggplot2)
library(purrr)

# Summarize proportion for each index
LLN_fev1_adults_GLIgl <- map_dfr(c(1,10), function(i) {
  refs_adult_all_races[[i]]$variables %>%
    group_by(race_text_nhanes, ref) %>%
    summarise(below_llm = mean(fev1_below_lln_GLIgl, na.rm = TRUE), .groups = "drop") %>%
    mutate(index = case_match(ref,
                              "reference" ~ "before exclusions",
                              "+ healthy diet" ~ "after exclusions")) %>%
    mutate(index = factor(index, levels=c("before exclusions",
                                 "after exclusions")))
})

# Plot
lln_fev1_adults <- ggplot(LLN_fev1_adults_GLIgl, aes(x = index, 
                          y = below_llm, 
                          color = race_text_nhanes,
                          group = race_text_nhanes)) +
  geom_line() +
  geom_point() +
  labs(
    title = "Adults",
    x = "",
    y = "FEV1 Below LLN",
    color = ""
  ) +
  scale_colour_brewer(palette = "Set2") +
  scale_y_continuous(labels = scales::percent_format(), limits = c(0, 0.15))  +
  theme_few() +
  theme(legend.position = "bottom")


# Summarize proportion for each index
LLN_fvc_adults_GLIgl <- map_dfr(c(1,10), function(i) {
  refs_adult_all_races[[i]]$variables %>%
    group_by(race_text_nhanes, ref) %>%
    summarise(below_llm = mean(fvc_below_lln_GLIgl, na.rm = TRUE), .groups = "drop") %>%
    mutate(index = case_match(ref,
                              "reference" ~ "before exclusions",
                              "+ healthy diet" ~ "after exclusions")) %>%
    mutate(index = factor(index, levels=c("before exclusions",
                                 "after exclusions")))
})

# Plot
lln_fvc_adults <-ggplot(LLN_fvc_adults_GLIgl, aes(x = index, 
                          y = below_llm, 
                          color = race_text_nhanes,
                          group = race_text_nhanes)) +
  geom_line() +
  geom_point() +
  labs(
    title = "",
    x = "",
    y = "FVC Below LLN",
    color = ""
  ) +
  scale_colour_brewer(palette = "Set2") +
  scale_y_continuous(labels = scales::percent_format(), limits = c(0, 0.15))  +
  theme_few() +
  theme(legend.position = "bottom")








# # Summarize proportion for each index
# LLN_fev1_adults_GLI2012 <- map_dfr(c(1,10), function(i) {
#   refs_adult_all_races[[i]]$variables %>%
#     group_by(race_text_nhanes, ref) %>%
#     summarise(below_llm = mean(fev1_below_lln_GLI, na.rm = TRUE), .groups = "drop") %>%
#     mutate(index = case_match(ref,
#                               "reference" ~ "before exclusions",
#                               "+ healthy diet" ~ "after exclusions")) %>%
#     mutate(index = factor(index, levels=c("before exclusions",
#                                  "after exclusions")))
# })
# 
# # Plot
# ggplot(LLN_fev1_adults_GLI2012, aes(x = index, 
#                             y = below_llm, 
#                             color = race_text_nhanes,
#                             group = race_text_nhanes)) +
#   geom_line() +
#   geom_point() +
#   labs(
#     title = "Proportion of FEV1 Below LLN - GLI 2012",
#     x = "",
#     y = "Proportion Below LLN",
#     color = "Race"
#   ) +
#   scale_y_continuous(labels = scales::percent_format(), limits = c(0, 0.15))  +
#   theme_few()

```

And now for kids:

```{r}
# Summarize proportion for each index
LLN_fev1_youth_GLIgl <- map_dfr(c(1,10), function(i) {
  refs_youth_all_races[[i]]$variables %>%
    group_by(race_text_nhanes, ref) %>%
    summarise(below_llm = mean(fev1_below_lln_GLIgl, na.rm = TRUE), .groups = "drop") %>%
    mutate(index = case_match(ref,
                              "reference" ~ "before exclusions",
                              "+ healthy diet" ~ "after exclusions")) %>%
    mutate(index = factor(index, levels=c("before exclusions",
                                 "after exclusions")))
})

# Plot
lln_fev1_youth <- ggplot(LLN_fev1_youth_GLIgl, aes(x = index, 
                          y = below_llm, 
                          color = race_text_nhanes,
                          group = race_text_nhanes)) +
  geom_line() +
  geom_point() +
  labs(
    title = "Children",
    x = "",
    y = "FEV1 Below LLN",
    color = ""
  ) +
  scale_colour_brewer(palette = "Set2") +
  scale_y_continuous(labels = scales::percent_format(), limits = c(0, 0.15))  +
  theme_few() +
  theme(legend.position = "bottom")


# Summarize proportion for each index
LLN_fvc_youth_GLIgl <- map_dfr(c(1,10), function(i) {
  refs_youth_all_races[[i]]$variables %>%
    group_by(race_text_nhanes, ref) %>%
    summarise(below_llm = mean(fvc_below_lln_GLIgl, na.rm = TRUE), .groups = "drop") %>%
    mutate(index = case_match(ref,
                              "reference" ~ "before exclusions",
                              "+ healthy diet" ~ "after exclusions")) %>%
    mutate(index = factor(index, levels=c("before exclusions",
                                 "after exclusions")))
})

# Plot
lln_fvc_youth <- ggplot(LLN_fvc_youth_GLIgl, aes(x = index, 
                          y = below_llm, 
                          color = race_text_nhanes,
                          group = race_text_nhanes)) +
  geom_line() +
  geom_point() +
  labs(
    title = "",
    x = "",
    y = "FVC Below LLN",
    color = ""
  ) +
  scale_colour_brewer(palette = "Set2") +
  scale_y_continuous(labels = scales::percent_format(), limits = c(0, 0.15))  +
  theme_few() +
  theme(legend.position = "bottom")

```

putting it together:

```{r}

figure4 <- 
  ((lln_fev1_youth + 
  lln_fev1_adults +
  lln_fvc_youth + 
  lln_fvc_adults +
  plot_layout(ncol = 2) +
  plot_layout(axes="collect") )/guide_area())  + 
  plot_annotation(tag_levels = 'A') + 
  plot_layout(guides = "collect")
  

figure4

```

## Repeat with NHANES III

```{r}

createCohortNHANESIII <- function (ageGroup, incomePovertyRatioOnly=FALSE, sex='all', BirthCountry='all', homeOwnershipOnly=FALSE, includedRace=c(3,4), leaveOneIn=FALSE) {
  if (!(ageGroup %in% c("adult", "children", "all_ages"))) 
    stop("Invalid age group")
  if (!(BirthCountry %in% c("all", "US", "Other countries"))) 
    stop("Invalid BirthCountry")
  if (!(sex %in% c("all", "male", "female"))) 
    stop("Invalid sex")
  

  nhanes <- readRDS("nhanes_2007_2012.rds") %>%
  as_survey_design(
    weights=MEC6YR,
    ids=SDMVPSU,
    strata=SDMVSTRA,
    nest=TRUE
  )
  
  if (AllostaticLoadOnly) {
    
    nhanes <- nhanes %>%
    mutate(
     mean_bp_sys=mean(c(bp_sys_1, bp_sys_2, bp_sys_3, bp_sys_4), na.rm = TRUE), 
     mean_bp_dias=mean(c(bp_dias_1, bp_dias_2, bp_dias_3, bp_dias_4), na.rm = TRUE), 
     als_crp                    = as.numeric((percent_rank(crp)                    >=0.75)),
     als_wbc                    = as.numeric((percent_rank(wbc)                    >=0.75)),
     als_glycohemoglobin        = as.numeric((percent_rank(glycohemoglobin)        >=0.75)),
     als_albumin_ug_ml          = as.numeric((percent_rank(albumin_ug_ml)          <=0.25)),
     als_creatinin_mg_dl        = as.numeric((percent_rank(creatinin_mg_dl)        >=0.75)),
     als_total_cholesterol_mg_dl= as.numeric((percent_rank(total_cholesterol_mg_dl)>=0.75)),
     als_hdl_mg_dl              = as.numeric((percent_rank(hdl_mg_dl)              <=0.25)),
     als_trigly_mg_dl           = as.numeric((percent_rank(trigly_mg_dl)           >=0.75)),
     als_bmi                    = as.numeric((percent_rank(bmi)                    >=0.75)),
     als_mean_bp_sys            = as.numeric((percent_rank(mean_bp_sys)            >=0.75)),
       als_mean_bp_dias         = as.numeric((percent_rank(mean_bp_dias)           >=0.75)),
       als_pulse_60_sec         = as.numeric((percent_rank(pulse_60_sec)           >=0.75)),
      ) %>%
      mutate(als_score = rowSums(srvyr::select(., als_crp, als_wbc, als_glycohemoglobin, als_albumin_ug_ml,
                                               als_creatinin_mg_dl, als_total_cholesterol_mg_dl, als_hdl_mg_dl, als_trigly_mg_dl,
                                               als_bmi, als_mean_bp_sys, als_mean_bp_dias, als_pulse_60_sec
                                               )$variables, na.rm = TRUE))

  }
  
  
  stopifnot((nhanes$variables %>% count()) == 30442) # Ensure we have the correct n
  stopifnot(((nhanes %>% srvyr::filter(race %in% c(3,4)))$variables %>% count()) == 18359) 
  stopifnot(((nhanes %>% drop_na(fev1_pre, fvc_pre))$variables  %>% count()) == 20050) 
  
  if (sex=='female') {
    warning('only females are included.')
    nhanes <- nhanes %>% srvyr::filter(sex==2)
  }
  
  if (sex=='male') {
    warning('only males are included.')
    nhanes <- nhanes %>% srvyr::filter(sex==1)
  }

  nhanes <- nhanes %>%
    mutate(fev1 = fev1_pre,
           fvc  = fvc_pre) %>%
    drop_na(fev1, fvc) %>%
    srvyr::filter(spiro_status_pre == 1) %>%
    srvyr::filter(fev1_quality_pre == "A" | fev1_quality_pre == "B") %>%
    srvyr::filter(fvc_quality_pre  == "A" | fvc_quality_pre  == "B") %>%
    mutate(
      race_spiro = case_match(
        race_text_nhanes,
        "Non-Hispanic White" ~ 1, 
        "Mexican American"   ~ 1,
        "Non-Hispanic Black" ~ 2,
        "Non-Hispanic Asian" ~ 4, 
        "Other Race - Including Multi-Racial" ~ 5,
        "Other Hispanic" ~ 1,
      ),
      fev1_lln_GLIgl = LLN_GLIgl(age=age, 
                                 height=height/100, 
                                 gender=sex,
                                 param="FEV1"),
      fev1_below_lln_GLIgl = fev1/1000 < fev1_lln_GLIgl,
      fev1_lln_GLI = LLN_GLI(age=age, 
                             height=height/100, 
                             gender=sex,
                             ethnicity=race_spiro,
                             param="FEV1"),
      fev1_below_lln_GLI = fev1/1000 < fev1_lln_GLI,
      fvc_lln_GLIgl = LLN_GLIgl(age=age, 
                                 height=height/100, 
                                 gender=sex,
                                 param="FVC"),
      fvc_below_lln_GLIgl = fvc/1000 < fvc_lln_GLIgl,
      fvc_lln_GLI = LLN_GLI(age=age, 
                             height=height/100, 
                             gender=sex,
                             ethnicity=race_spiro,
                             param="FVC"),
      fvc_below_lln_GLI = fvc/1000 < fvc_lln_GLI,
      
      )
  
    
    # mutate(race_text_nhanes = str_remove(race_text_nhanes, "Non-Hispanic "))
  
  message(paste0("NHANES N (excluding missing or low quality spiro: ", 
                 (nhanes$variables %>% count())))
  
  if (BirthCountry=='all'){
      nhanes_bw <- nhanes %>%
        srvyr::filter(race %in% includedRace) %>%
        mutate(race=factor(race, levels=includedRace))
  } else  {
          nhanes_bw <- nhanes %>%
            srvyr::filter(race %in% includedRace) %>%
            srvyr::filter(birth_country==BirthCountry) %>%
            mutate(race=factor(race, levels=includedRace))

  } 

  message(paste0("NHANES included races N (excluding missing or low quality spiro: ", 
                 (nhanes_bw$variables %>% count())))
  
if (ageGroup=="adult") {
nhanes_bw <- nhanes_bw %>%
  srvyr::filter(age>=20)

  message(paste0(ageGroup, "-NHANES : ", 
                 (nhanes_bw$variables %>% count())))
}
  
if (ageGroup=="children") {
nhanes_bw <- nhanes_bw %>%
  srvyr::filter(age<20)

  message(paste0(ageGroup, "-NHANES : ", 
                 (nhanes_bw$variables %>% count())))
}
  
if (ageGroup=="all_ages") {

  message(paste0(ageGroup, "-NHANES : ", 
                 (nhanes_bw$variables %>% count())))
}
 
#vis_miss(nhanes_bw, warn_large_data = F)

ref0 <- nhanes_bw %>%
   mutate(
        sex_text = case_match(sex,
                              "1" ~ "Male",
                              "2" ~ "Female" ),
        ref="population"
        ) 
  

ref0$variables %>%
  group_by(race) %>%
  count()

ref1 <- ref0 %>%
  srvyr::filter ((is.na(current_smoke) | (current_smoke == "3")) &
         (is.na(ever_100_smoke) | (ever_100_smoke != "1")) &
         (is.na(last_5_days_cigarettes) |  (last_5_days_cigarettes != "1")) &
         (is.na(last_5_days_pipes) | (last_5_days_pipes != "1")) &
         (is.na(last_5_days_cigars) | (last_5_days_cigars != "1")) &
         (is.na(ever_asthma) | (ever_asthma !="1")) &
         (is.na(ever_bronchitis) | (ever_bronchitis != "1")) &
         (is.na(ever_emphysema) | (ever_emphysema != "1")) &
         (is.na(cough_3_month) | (cough_3_month!=1)) & 
         (is.na(phlegm_3_month) | (phlegm_3_month!=1)) & 
         (is.na(wheezing_past_yr) | (wheezing_past_yr!=1)) & 
         (is.na(dry_cough_night_past_yr) | (dry_cough_night_past_yr!=1))) %>%
  mutate(ref="reference")

if (incomePovertyRatioOnly) {
  ref2 <- ref1 %>% srvyr::filter(is.na(income_poverty_ratio) | (income_poverty_ratio>=1)) %>%
  mutate(ref="income_poverty_ratio>=1")
  ref3 <- ref2 %>% srvyr::filter(is.na(income_poverty_ratio) | (income_poverty_ratio>=1.5)) %>%
  mutate(ref="income_poverty_ratio>=1.5")
  ref4 <- ref3 %>% srvyr::filter(is.na(income_poverty_ratio) | (income_poverty_ratio>=2)) %>%
  mutate(ref="income_poverty_ratio>=2")
  ref5 <- ref4 %>% srvyr::filter(is.na(income_poverty_ratio) | (income_poverty_ratio>=2.5))  %>%
  mutate(ref="income_poverty_ratio>=2.5")
  ref6 <- ref5 %>% srvyr::filter(is.na(income_poverty_ratio) | (income_poverty_ratio>=3)) %>%
  mutate(ref="income_poverty_ratio>=3")
  ref7 <- ref6 %>% srvyr::filter(is.na(income_poverty_ratio) | (income_poverty_ratio>=3.5))  %>%
  mutate(ref="income_poverty_ratio>=3.5")
  ref8 <- ref7 %>% srvyr::filter(is.na(income_poverty_ratio) | (income_poverty_ratio>=4))  %>%
  mutate(ref="income_poverty_ratio>=4")
  ref9 <- ref8 %>% srvyr::filter(is.na(income_poverty_ratio) | (income_poverty_ratio>=4.5))  %>%
  mutate(ref="income_poverty_ratio>=4.5")
  ref10<- ref9 %>% srvyr::filter(is.na(income_poverty_ratio) | (income_poverty_ratio>=5))  %>%
  mutate(ref="income_poverty_ratio>=5")
  refs <- list(ref1, ref2, ref3, ref4, ref5, ref6, ref7, ref8, ref9, ref10)

}


if (AllostaticLoadOnly) {
  ref2 <- ref1 %>% srvyr::filter(is.na(als_score) | (als_score<=8)) %>%
  mutate(ref="als_score<=8")
  ref3 <- ref2 %>% srvyr::filter(is.na(als_score) | (als_score<=7)) %>%
  mutate(ref="als_score<=7")
  ref4 <- ref3 %>% srvyr::filter(is.na(als_score) | (als_score<=6)) %>%
  mutate(ref="als_score<=6")
  ref5 <- ref4 %>% srvyr::filter(is.na(als_score) | (als_score<=5))  %>%
  mutate(ref="als_score<=5")
  ref6 <- ref5 %>% srvyr::filter(is.na(als_score) | (als_score<=4)) %>%
  mutate(ref="als_score<=4")
  ref7 <- ref6 %>% srvyr::filter(is.na(als_score) | (als_score<=3))  %>%
  mutate(ref="als_score<=3")
  ref8 <- ref7 %>% srvyr::filter(is.na(als_score) | (als_score<=2))  %>%
  mutate(ref="als_score<=2")
  ref9 <- ref8 %>% srvyr::filter(is.na(als_score) | (als_score<=1))  %>%
  mutate(ref="als_score<=1")
  ref10<- ref9 %>% srvyr::filter(is.na(als_score) | (als_score<=0))  %>%
  mutate(ref="als_score<=0")
  refs <- list(ref1, ref2, ref3, ref4, ref5, ref6, ref7, ref8, ref9, ref10)

}


if (homeOwnershipOnly) {
  ref2 <- ref1 %>% 
    srvyr::filter(is.na(home_ownership) | (home_ownership==1)) %>%
  mutate(ref="home owner")
  refs <- list(ref1, ref2)

}

if (leaveOneIn) {
  ref2 <- ref1 %>%
    srvyr::filter((is.na(mineral_dusts) | (mineral_dusts!=1)) & 
         (is.na(organic_dusts)   | (organic_dusts!=1)) & 
         (is.na(exhaust_fumes)   | (exhaust_fumes!=1)) & 
         (is.na(other_fumes)     | (other_fumes!=1))) %>%
  mutate(ref="job unexposed")
  
  
ref3 <- ref1 %>%
      srvyr::filter((is.na(vigorous_work) | (vigorous_work==1)) | 
         (is.na(vigorous_recreational)   | (vigorous_recreational==1)) | 
         (is.na(moderate_work)   | (moderate_work==1)) | 
         (is.na(moderate_recreational)   | (moderate_recreational==1)))  %>%
  mutate(ref="physically active")

ref4 <- ref1 %>%
      srvyr::filter((is.na(maternal_smoke) | (maternal_smoke!=1))) %>% #TODO Maternal smoke not available for those over 15 years
  mutate(ref="no maternal smoke")
  
ref5 <- ref1 %>%  
      srvyr::filter((is.na(smoker_in_household) | (smoker_in_household != "1"))) %>%
      mutate(ref="no 2ndhand smoke")

ref6 <- ref1 %>%
      srvyr::filter((is.na(bmi) | (bmi<=30))) %>%
  mutate(ref="not obese")

ref7 <- ref1 %>%
    srvyr::filter(is.na(home_ownership) | (home_ownership==1))  %>%
  mutate(ref="homeowner")

ref8 <- ref1 %>%
     srvyr::filter((is.na(has_insurance) | 
               (has_insurance==1)))  %>%
  mutate(ref="insured")

if (ageGroup=="adult") {
  ref9 <- ref1 %>%
    srvyr::filter(is.na(education_adults) | (education_adults %in% c(4,5)))  %>%
  mutate(ref="educated")
}

if (ageGroup=="children") {
  ref9 <- ref1 %>%
    srvyr::filter(is.na(now_attending_school) | (now_attending_school != 3)| (age<6))  %>%
  mutate(ref="educated")
}

ref10 <- ref1 %>%
    srvyr::filter((is.na(healthy_diet) | 
               (healthy_diet==1) | 
               (healthy_diet==2) | 
               (healthy_diet==3)))  %>%
  mutate(ref="healthy diet")
}

if (!incomePovertyRatioOnly & !homeOwnershipOnly & !AllostaticLoadOnly &!leaveOneIn) {
ref2 <- ref1 %>%
    srvyr::filter((is.na(mineral_dusts) | (mineral_dusts!=1)) & 
         (is.na(organic_dusts)   | (organic_dusts!=1)) & 
         (is.na(exhaust_fumes)   | (exhaust_fumes!=1)) & 
         (is.na(other_fumes)     | (other_fumes!=1))) %>%
  mutate(ref="+ job unexposed")
  
  
ref3 <- ref2 %>%
      srvyr::filter((is.na(vigorous_work) | (vigorous_work==1)) | 
         (is.na(vigorous_recreational)   | (vigorous_recreational==1)) | 
         (is.na(moderate_work)   | (moderate_work==1)) | 
         (is.na(moderate_recreational)   | (moderate_recreational==1)))  %>%
  mutate(ref="+ physically active")

ref4 <- ref3 %>%
      srvyr::filter((is.na(maternal_smoke) | (maternal_smoke!=1))) %>% #TODO Maternal smoke not available for those over 15 years
  mutate(ref="+ no maternal smoke")
  
ref5 <- ref4 %>%  
      srvyr::filter((is.na(smoker_in_household) | (smoker_in_household != "1"))) %>%
      mutate(ref="+ no 2ndhand smoke")

ref6 <- ref5 %>%
      srvyr::filter((is.na(bmi) | (bmi<=30))) %>%
  mutate(ref="+ not obese")

ref7 <- ref6 %>%
    srvyr::filter(is.na(home_ownership) | (home_ownership==1))  %>%
  mutate(ref="+ homeowner")

ref8 <- ref7 %>%
     srvyr::filter((is.na(has_insurance) | 
               (has_insurance==1)))  %>%
  mutate(ref="+ insured")

if (ageGroup=="adult") {
  ref9 <- ref8 %>%
  srvyr::filter(is.na(education_adults) | (education_adults %in% c(4,5)))  %>%
  mutate(ref="+ educated")
}

if (ageGroup=="children") {
  ref9 <- ref8 %>%
    filter(is.na(now_attending_school) | (now_attending_school != 3)| (age<6))  %>%
  mutate(ref="+ educated")
}

ref10 <- ref9 %>%
     srvyr::filter((is.na(healthy_diet) | 
               (healthy_diet==1) | 
               (healthy_diet==2) | 
               (healthy_diet==3)))  %>%
  mutate(ref="+ healthy diet")


  ref11 <- ref10 %>%
     srvyr::filter((is.na(lang_home_hispanic) | 
               (lang_home_hispanic==4) | 
               (lang_home_hispanic==5)))  %>%
     srvyr::filter((is.na(lang_home_asian) | 
               (lang_home_asian==4) | 
               (lang_home_asian==5)))  %>%
     srvyr::filter((is.na(lang_home_en_bw) | 
               (lang_home_en_bw==1)))  %>%
  mutate(ref="+ English at home")
  

}


refs <- list(ref1, ref2, ref3, ref4, ref5, ref6, ref7, ref8, ref9, ref10)


return(refs)
}


```
